sudo: required

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull heltai/deal2lkit
- docker run -P -v `pwd`:/home/dealii/WaveBEM  heltai/deal2lkit /bin/sh -c "cd WaveBEM; ./scripts/check_indentation.sh"

script:
- docker run -P -v `pwd`:/home/dealii/WaveBEM heltai/deal2lkit /bin/sh -c "mkdir WaveBEM/build; cd WaveBEM/build; cmake -GNinja ../; ninja -j1"
- docker run -P -v `pwd`:/home/dealii/WaveBEM heltai/deal2lkit /bin/sh -c "cd WaveBEM/build; ninja setup_tests; ctest -j1;"
